### ISSUE TITLE
How to handle it error about python3 bin/train.py -cn lama-fourier location=places_standard?

### ISSUE THREAD

**Issue by mumingerlai** [advimman/lama#225]
[2023-04-06 16:36:06,834][__main__][CRITICAL] - Training failed due to unexpected EOF, expected 4658175 more bytes. The file might be corrupted.:
Traceback (most recent call last):
  File "bin/train.py", line 50, in main
    training_model = make_training_model(config)
  File "/home/zrr/lama/saicinpainting/training/trainers/__init__.py", line 22, in make_training_model
    return cls(config, **kwargs)
  File "/home/zrr/lama/saicinpainting/training/trainers/default.py", line 32, in __init__
    super().__init__(*args, **kwargs)
  File "/home/zrr/lama/saicinpainting/training/trainers/base.py", line 110, in __init__
    self.loss_resnet_pl = ResNetPL(**self.config.losses.resnet_pl)
  File "/home/zrr/lama/saicinpainting/training/losses/perceptual.py", line 96, in __init__
    segmentation=segmentation)
  File "/home/zrr/lama/models/ade20k/base.py", line 136, in get_encoder
    return ModelBuilder.build_encoder(arch=arch_encoder, fc_dim=fc_dim, weights=path)
  File "/home/zrr/lama/models/ade20k/base.py", line 94, in build_encoder
    torch.load(weights, map_location=lambda storage, loc: storage), strict=False)
  File "/home/zrr/.conda/envs/lama/lib/python3.6/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/zrr/.conda/envs/lama/lib/python3.6/site-packages/torch/serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 4658175 more bytes. The file might be corrupted.

**Comment by senya-ashukha** [comment]
Hey, unfortunately not enough info to help
