### ISSUE TITLE
KeyError: 'href' occur When I use yadisk to download big-lama.zip 

### ISSUE THREAD

**Issue by 00Klein** [advimman/lama#229]
this is my code:
curl -L $(yadisk-direct https://disk.yandex.ru/d/ouP6l8VJ0HpMZg) -o big-lama.zip

And then:
Traceback (most recent call last):
  File "/root/anaconda3/envs/inpaintanything/bin/yadisk-direct", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/inpaintanything/lib/python3.9/site-packages/wldhx/yadisk_direct/main.py", line 23, in main
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/root/anaconda3/envs/inpaintanything/lib/python3.9/site-packages/wldhx/yadisk_direct/main.py", line 23, in <listcomp>
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/root/anaconda3/envs/inpaintanything/lib/python3.9/site-packages/wldhx/yadisk_direct/main.py", line 12, in get_real_direct_link
    return pk_request.json()['href']
KeyError: 'href'
curl: no URL specified!
curl: try 'curl --help' for more information

**Comment by AshishBora** [comment]
This is because the file hosted at https://disk.yandex.ru/d/ouP6l8VJ0HpMZg has exceeded download limit. You can create your own Yandex account and that allows you to download the models via the UI.

**Comment by osalbahr** [comment]
@AshishBora this is what I get now -- is there a way to git the files elsewhere?

<img width="1032" alt="Screenshot 2023-10-24 at 3 37 14 PM" src="https://github.com/advimman/lama/assets/54853250/5020e268-8373-45ae-ab2f-21eeacf23cb6">

**Comment by senya-ashukha** [comment]
Sorry for inconvenience ---- try that https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link ! and we will fix the repo! TY!
