### ISSUE TITLE
my_dataset training error

### ISSUE THREAD

**Issue by kwanwoo02** [advimman/lama#257]
Hi, I want to train my dataset, but it doesn't work like this
Please help me.

# My error
``` 
Detectron v2 is not installed
bin/train.py:29: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path='../configs/training', config_name='lama-fourier.yaml')
/home/ubuntu/.local/lib/python3.6/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'lama-fourier.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/ubuntu/.local/lib/python3.6/site-packages/hydra/core/default_element.py:128: UserWarning: In 'hydra/overrides': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/ubuntu/.local/lib/python3.6/site-packages/hydra/core/default_element.py:128: UserWarning: In 'trainer/any_gpu_large_ssim_ddp_final': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/ubuntu/.local/lib/python3.6/site-packages/hydra/core/default_element.py:128: UserWarning: In 'evaluator/default_inpainted': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/ubuntu/.local/lib/python3.6/site-packages/hydra/core/default_element.py:128: UserWarning: In 'visualizer/directory': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/ubuntu/.local/lib/python3.6/site-packages/hydra/core/default_element.py:128: UserWarning: In 'optimizers/default_optimizers': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/ubuntu/.local/lib/python3.6/site-packages/hydra/core/default_element.py:128: UserWarning: In 'discriminator/pix2pixhd_nlayer': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/ubuntu/.local/lib/python3.6/site-packages/hydra/core/default_element.py:128: UserWarning: In 'generator/ffc_resnet_075': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/ubuntu/.local/lib/python3.6/site-packages/hydra/core/default_element.py:128: UserWarning: In 'data/abl-04-256-mh-dist': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "bin/train.py", line 72, in <module>
    main()
  File "/home/ubuntu/workspace/kwanwoo/webtoon/Inpainting/lama/bin/saicinpainting/utils.py", line 163, in new_main
    main_func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hydra/main.py", line 95, in decorated_main
    config_name=config_name,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hydra/_internal/utils.py", line 401, in _run_hydra
    overrides=overrides,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hydra/_internal/utils.py", line 458, in _run_app
    lambda: hydra.run(
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hydra/_internal/utils.py", line 301, in run_and_report
    raise ex
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    overrides=overrides,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 127, in run
    configure_logging=with_log_configuration,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/hydra/core/utils.py", line 116, in run_job
    output_dir = str(OmegaConf.select(config, job_dir_key))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/omegaconf.py", line 682, in select
    format_and_raise(node=cfg, key=key, value=None, cause=e, msg=str(e))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/omegaconf.py", line 679, in select
    throw_on_missing=throw_on_missing,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/_impl.py", line 63, in select_value
    absolute_key=absolute_key,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/_impl.py", line 96, in select_node
    throw_on_resolution_failure=throw_on_resolution_failure,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/base.py", line 536, in _select_impl
    memo=memo,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/base.py", line 725, in _maybe_resolve_interpolation
    memo=memo if memo is not None else set(),
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/base.py", line 585, in _resolve_interpolation_from_parse_tree
    parse_tree=parse_tree, node=value, key=key, memo=memo
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/grammar/gen/OmegaConfGrammarParser.py", line 1041, in accept
    return visitor.visitInterpolationResolver(self)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/grammar_visitor.py", line 182, in visitInterpolationResolver
    args_str=tuple(args_str),
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/base.py", line 755, in resolver_interpolation_callback
    inter_args_str=args_str,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/omegaconf/base.py", line 703, in _evaluate_custom_resolver
    f"Unsupported interpolation type {inter_type}"
omegaconf.errors.UnsupportedInterpolationType: Unsupported interpolation type env
    full_key: hydra.run.dir
    object_type=dict
```

**Comment by a-lasri** [comment]
I've never encountered this specific error before. To potentially assist, please provide the exact command you executed, the Hydra version (check with pip show hydra-core), and the contents of the lama-fourier configuration file.

**Comment by kwanwoo02** [comment]
@a-lasri Thank you for your reply. 
My hydra version is 1.2.0 

The configuration is as follows:

execution command
```
python3 bin/train.py -cn lama-fourier location=my_dataset data.batch_size=10
```
lama-fourier
```
run_title: ''

training_model:
  kind: default
  visualize_each_iters: 1000
  concat_mask: true
  store_discr_outputs_for_vis: true
losses:
  l1:
    weight_missing: 0
    weight_known: 10
  perceptual:
    weight: 0
  adversarial:
    kind: r1
    weight: 10
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  feature_matching:
    weight: 100
  resnet_pl:
    weight: 30
    weights_path: ${env:TORCH_HOME}

defaults:
  - location: docker
  - data: abl-04-256-mh-dist
  - generator: ffc_resnet_075
  - discriminator: pix2pixhd_nlayer
  - optimizers: default_optimizers
  - visualizer: directory
  - evaluator: default_inpainted
  - trainer: any_gpu_large_ssim_ddp_final
  - hydra: overrides
```

**Comment by a-lasri** [comment]
Please ensure that you switch to version 1.1.0 as specified in the requirements.txt and then retest. Additionally, don't forget to set up the necessary environment variables:

export TORCH_HOME=$(pwd)
export PYTHONPATH=$(pwd)

**Comment by kwanwoo02** [comment]
Thank you. I followed the answer and succeeded. I think it was the Hydra version that was the problem.

**Comment by qwexacc** [comment]
> 我以前从未遇到过这个特定的错误。为了提供可能的帮助，请提供您执行的确切命令、Hydra 版本（使用 pip show hydra-core 检查）以及 lama-fourier 配置文件的内容。



> hydra-core

Hello, excuse me, my hydra-core version is 1.1.0, but there are still errors, could you please help me?
