### ISSUE TITLE
ImportError: cannot import name 'DualIAATransform' from 'albumentations'

### ISSUE THREAD

**Issue by Abbsalehi** [advimman/lama#301]
I am trying to train the model but I got this error:

```
Traceback (most recent call last):
  File "/home/user/PycharmProjects/lama/bin/train.py", line 21, in <module>
    from saicinpainting.training.trainers import make_training_model
  File "/home/user/PycharmProjects/lama/saicinpainting/training/trainers/__init__.py", line 3, in <module>
    from saicinpainting.training.trainers.default import DefaultInpaintingTrainingModule
  File "/home/user/PycharmProjects/lama/saicinpainting/training/trainers/default.py", line 7, in <module>
    from saicinpainting.training.data.datasets import make_constant_area_crop_params
  File "/home/user/PycharmProjects/lama/saicinpainting/training/data/datasets.py", line 19, in <module>
    from saicinpainting.training.data.aug import IAAAffine2, IAAPerspective2
  File "/home/user/PycharmProjects/lama/saicinpainting/training/data/aug.py", line 1, in <module>
    from albumentations import DualIAATransform, to_tuple
ImportError: cannot import name 'DualIAATransform' from 'albumentations'
```

**Comment by Abbsalehi** [comment]
I solved it using

`pip install albumentations==0.5.2`
