### ISSUE TITLE
Error finetuning the big-lama-with-discr model

### ISSUE THREAD

**Issue by xv5kVu4FN** [advimman/lama#308]
Hi,
I have downloaded the models from [Google Drive](https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link) and I'm trying to finetune the _big-lama-with-discr_ with a custom dataset.

I'm launching the `train` script like this: `python bin/train.py -cn lama-fourier location=lama_training_dataset.yml trainer.kwargs.resume_from_checkpoint=/home/me/lama/models/LaMa_models/big-lama-with-discr/models/best.ckpt`

Unfortunately, the training ends with an error (full error log is attached):
```
4-04-03 11:31:16,537][__main__][CRITICAL] - Training failed due to Error(s) in loading state_dict for DefaultInpaintingTrainingModule:
        Missing key(s) in state_dict: "generator.model.15.weight", "generator.model.15.bias", "generator.model.16.weight", "generator.model.16.bias", "generator.model.16.running_mean", "generator.model.16.running_var", "generator.model.18.weight", "generator.model.18.bias", "generator.model.19.weight", "generator.model.19.bias", "generator.model.19.running_mean", "generator.model.19.running_var", "generator.model.21.weight", "generator.model.21.bias", "generator.model.22.weight", "generator.model.22.bias", "generator.model.22.running_mean", "generator.model.22.running_var", "loss_resnet_pl.impl.conv1.weight", "loss_resnet_pl.impl.bn1.weight", "loss_resnet_pl.impl.bn1.bias", "loss_resnet_pl.impl.bn1.running_mean", 
```

Can the _big-lama-with-discr_ model be finetuned? Have I made a mistake in the training?

Any help is appreciated.
Kind regards!

[error_finetune_big_lama_with_discr.txt](https://github.com/advimman/lama/files/14850061/error_finetune_big_lama_with_discr.txt)

**Comment by SofyanaB** [comment]
@xv5kVu4FN Hello! I faced the same problem. Did you manage to solve it?

**Comment by SofyanaB** [comment]
@xv5kVu4FN I managed to solve the problem. Make sure that in the config file that is used for training:  
generator: ffc_resnet_075
And in lama/configs/training/generator/ffc_resnet_075.yaml 
n_blocks: 18

**Comment by xv5kVu4FN** [comment]
Hi @SofyanaB!
I'm using the `lama-fourier` config, which in turn uses the `fcc_resnet_075` generator. I have set `n_blocks: 18`, like you said, but I'm still facing the same problem.

What is your configuration?

```shell
$ python bin/train.py -cn lama-fourier location=lama_training_dataset.yml trainer.kwargs.max_epochs=5 trainer.kwargs.resume_from_checkpoint=/home/me/lama/models/LaMa_models/big-lama-with-discr/models/best.ckpt

Traceback (most recent call last):
  File "bin/train.py", line 90, in main
    trainer.fit(training_model)
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 602, in run_train
    self._pre_training_routine()
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 593, in _pre_training_routine
    self.checkpoint_connector.restore_weights()
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 73, in restore_weights
    self.restore(self.trainer.resume_from_checkpoint, on_gpu=self.trainer._device_type == DeviceType.GPU)
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 100, in restore
    self.restore_model_state(model, checkpoint)
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 124, in restore_model_state
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/me/.conda/envs/lama/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DefaultInpaintingTrainingModule:
        Unexpected key(s) in state_dict: "loss_segm_pl.impl.conv1.weight", "loss_segm_pl.impl.bn1.weight", "loss_segm_pl.impl.bn1.bias", "loss_segm_pl.impl.bn1.running_mean", "loss_segm_pl.impl.bn1.running_var", 
"loss_segm_pl.impl.bn1.num_batches_tracked", "loss_segm_pl.impl.conv2.weight", "loss_segm_pl.impl.bn2.weight", "loss_segm_pl.impl.bn2.bias", "loss_segm_pl.impl.bn2.running_mean", "loss_segm_pl.impl.bn2.running_var", "loss_segm_pl.impl.bn2.num_batches_tracked", "loss_segm_pl.impl.conv3.weight", "loss_segm_pl.impl.bn3.weight", "loss_segm_pl.impl.bn3.bias", "loss_segm_pl.impl.bn3.running_mean", "loss_segm_pl.impl.bn3.running_var", "loss_segm_pl.impl.bn3.num_batches_tracked", "loss_segm_pl.impl.layer1.0.conv1.weight", "loss_segm_pl.impl.layer1.0.bn1.weight", "loss_segm_pl.impl.layer1.0.bn1.bias", "loss_segm_pl.impl.layer1.0.bn1.running_mean", "loss_segm_pl.impl.layer1.0.bn1.running_var", "loss_segm_pl.impl.layer1.0.bn1.num_batches_tracked", "loss_segm_pl.impl.layer1.0.conv2.weight", "loss_segm_pl.impl.layer1.0.bn2.weight", "loss_segm_pl.impl.layer1.0.bn2.bias", "loss_segm_pl.impl.layer1.0.bn2.running_mean", "loss_segm_pl.impl.layer1.0.bn2.running_var", "loss_segm_pl.impl.layer1.0.bn2.num_batches_tracked", "loss_segm_pl.impl.layer1.0.conv3.weight", 
"loss_segm_pl.impl.layer1.0.bn3.weight", "loss_segm_pl.impl.layer1.0.bn3.bias", "loss_segm_pl.impl.layer1.0.bn3.running_mean", "loss_segm_pl.impl.layer1.0.bn3.running_var", "loss_segm_pl.impl.layer1.0.bn3.num_batches_tracked", "loss_segm_pl.impl.layer1.0.downsample.0.weight", "loss_segm_pl.impl.layer1.0.downsample.1.weight", "loss_segm_pl.impl.layer1.0.downsample.1.bias", "loss_segm_pl.impl.layer1.0.downsample.1.running_mean", "loss_segm_pl.impl.layer1.0.downsample.1.running_var", "loss_segm_pl.impl.layer1.0.downsample.1.num_batches_tracked", "loss_segm_pl.impl.layer1.1.conv1.weight", "loss_segm_pl.impl.layer1.1.bn1.weight", "loss_segm_pl.impl.layer1.1.bn1.bias", "loss_segm_pl.impl.layer1.1.bn1.running_mean", "loss_segm_pl.impl.layer1.1.bn1.running_var", "loss_segm_pl.impl.layer1.1.bn1.num_batches_tracked", "loss_segm_pl.impl.layer1.1.conv2.weight", "loss_segm_pl.impl.layer1.1.bn2.weight", "loss_segm_pl.impl.layer1.1.bn2.bias", "loss_segm_pl.impl.layer1.1.bn2.running_mean", "loss_segm_pl.impl.layer1.1.bn2.running_var", "loss_segm_pl.impl.layer1.1.bn2.num_batches_tracked", "loss_segm_pl.impl.layer1.1.conv3.weight", "loss_segm_pl.impl.layer1.1.bn3.weight", "loss_segm_pl.impl.layer1.1.bn3.bias", "loss_segm_pl.impl.layer1.1.bn3.running_mean", "loss_segm_pl.impl.layer1.1.bn3.running_var", "loss_segm_pl.impl.layer1.1.bn3.num_batches_tracked", "loss_segm_pl.impl.layer1.2.conv1.weight", "loss_segm_pl.impl.layer1.2.bn1.weight", "loss_segm_pl.impl.layer1.2.bn1.bias", "loss_segm_pl.impl.layer1.2.bn1.running_mean", "loss_segm_pl.impl.layer1.2.bn1.running_var", "loss_segm_pl.impl.layer1.2.bn1.num_batches_tracked", "loss_segm_pl.impl.layer1.2.conv2.weight", "loss_segm_pl.impl.layer1.2.bn2.weight", "loss_segm_pl.impl.layer1.2.bn2.bias", "loss_segm_pl.impl.layer1.2.bn2.running_mean", "loss_segm_pl.impl.layer1.2.bn2.running_var", "loss_segm_pl.impl.layer1.2.bn2.num_batches_tracked", "loss_segm_pl.impl.layer1.2.conv3.weight", "loss_segm_pl.impl.layer1.2.bn3.weight", "loss_segm_pl.impl.layer1.2.bn3.bias", "loss_segm_pl.impl.layer1.2.bn3.running_mean", "loss_segm_pl.impl.layer1.2.bn3.running_var", "loss_segm_pl.impl.layer1.2.bn3.num_batches_tracked", "loss_segm_pl.impl.layer2.0.conv1.weight", "loss_segm_pl.impl.layer2.0.bn1.weight", "loss_segm_pl.impl.layer2.0.bn1.bias", "loss_segm_pl.impl.layer2.0.bn1.running_mean", "loss_segm_pl.impl.layer2.0.bn1.running_var", "loss_segm_pl.impl.layer2.0.bn1.num_batches_tracked", "loss_segm_pl.impl.layer2.0.conv2.weight", "loss_segm_pl.impl.layer2.0.bn2.weight", "loss_segm_pl.impl.layer2.0.bn2.bias", "loss_segm_pl.impl.layer2.0.bn2.running_mean", "loss_segm_pl.impl.layer2.0.bn2.running_var", "loss_segm_pl.impl.layer2.0.bn2.num_batches_tracked", "loss_segm_pl.impl.layer2.0.conv3.weight", "loss_segm_pl.impl.layer2.0.bn3.weight", "loss_segm_pl.impl.layer2.0.bn3.bias", "loss_segm_pl.impl.layer2.0.bn3.running_mean", "loss_segm_pl.impl.layer2.0.bn3.running_var", "loss_segm_pl.impl.layer2.0.bn3.num_batches_tracked", "loss_segm_pl.impl.layer2.0.downsample.0.weight", "loss_segm_pl.impl.layer2.0.downsample.1.weight", "loss_segm_pl.impl.layer2.0.downsample.1.bias", "loss_segm_pl.impl.layer2.0.downsample.1.running_mean", "loss_segm_pl.impl.layer2.0.downsample.1.running_var", "loss_segm_pl.impl.layer2.0.downsample.1.num_batches_tracked", "loss_segm_pl.impl.layer2.1.conv1.weight", "loss_segm_pl.impl.layer2.1.bn1.weight", "loss_segm_pl.impl.layer2.1.bn1.bias", "loss_segm_pl.impl.layer2.1.bn1.running_mean", "loss_segm_pl.impl.layer2.1.bn1.running_var", "loss_segm_pl.impl.layer2.1.bn1.num_batches_tracked", "loss_segm_pl.impl.layer2.1.conv2.weight", "loss_segm_pl.impl.layer2.1.bn2.weight", "loss_segm_pl.impl.layer2.1.bn2.bias", "loss_segm_pl.impl.layer2.1.bn2.running_mean", "loss_segm_pl.impl.layer2.1.bn2.running_var", "loss_segm_pl.impl.layer2.1.bn2.num_batches_tracked", "loss_segm_pl.impl.layer2.1.conv3.weight", "loss_segm_pl.impl.layer2.1.bn3.weight", "loss_segm_pl.impl.layer2.1.bn3.bias", "loss_segm_pl.impl.layer2.1.bn3.running_mean", "loss_segm_pl.impl.layer2.1.bn3.running_var", "loss_segm_pl.impl.layer2.1.bn3.num_batches_tracked", "loss_segm_pl.impl.layer2.2.conv1.weight", "loss_segm_pl.impl.layer2.2.bn1.weight", "loss_segm_pl.impl.layer2.2.bn1.bias", "loss_segm_pl.impl.layer2.2.bn1.running_mean", "loss_segm_pl.impl.layer2.2.bn1.running_var", "loss_segm_pl.impl.layer2.2.bn1.num_batches_tracked", "loss_segm_pl.impl.layer2.2.conv2.weight", "loss_segm_pl.impl.layer2.2.bn2.weight", "loss_segm_pl.impl.layer2.2.bn2.bias", "loss_segm_pl.impl.layer2.2.bn2.running_mean", "loss_segm_pl.impl.layer2.2.bn2.running_var", "loss_segm_pl.impl.layer2.2.bn2.num_batches_tracked", "loss_segm_pl.impl.layer2.2.conv3.weight", "loss_segm_pl.impl.layer2.2.bn3.weight", "loss_segm_pl.impl.layer2.2.bn3.bias", "loss_segm_pl.impl.layer2.2.bn3.running_mean", "loss_segm_pl.impl.layer2.2.bn3.running_var", "loss_segm_pl.impl.layer2.2.bn3.num_batches_tracked", "loss_segm_pl.impl.layer2.3.conv1.weight", "loss_segm_pl.impl.layer2.3.bn1.weight", "loss_segm_pl.impl.layer2.3.bn1.bias", "loss_segm_pl.impl.layer2.3.bn1.running_mean", "loss_segm_pl.impl.layer2.3.bn1.running_var", "loss_segm_pl.impl.layer2.3.bn1.num_batches_tracked", "loss_segm_pl.impl.layer2.3.conv2.weight", "loss_segm_pl.impl.layer2.3.bn2.weight", "loss_segm_pl.impl.layer2.3.bn2.bias", "loss_segm_pl.impl.layer2.3.bn2.running_mean", "loss_segm_pl.impl.layer2.3.bn2.running_var", "loss_segm_pl.impl.layer2.3.bn2.num_batches_tracked", "loss_segm_pl.impl.layer2.3.conv3.weight", "loss_segm_pl.impl.layer2.3.bn3.weight", "loss_segm_pl.impl.layer2.3.bn3.bias", "loss_segm_pl.impl.layer2.3.bn3.running_mean", "loss_segm_pl.impl.layer2.3.bn3.running_var", "loss_segm_pl.impl.layer2.3.bn3.num_batches_tracked", "loss_segm_pl.impl.layer3.0.conv1.weight", "loss_segm_pl.impl.layer3.0.bn1.weight", "loss_segm_pl.impl.layer3.0.bn1.bias", "loss_segm_pl.impl.layer3.0.bn1.running_mean", "loss_segm_pl.impl.layer3.0.bn1.running_var", "loss_segm_pl.impl.layer3.0.bn1.num_batches_tracked", "loss_segm_pl.impl.layer3.0.conv2.weight", "loss_segm_pl.impl.layer3.0.bn2.weight", "loss_segm_pl.impl.layer3.0.bn2.bias", "loss_segm_pl.impl.layer3.0.bn2.running_mean", "loss_segm_pl.impl.layer3.0.bn2.running_var", "loss_segm_pl.impl.layer3.0.bn2.num_batches_tracked", "loss_segm_pl.impl.layer3.0.conv3.weight", "loss_segm_pl.impl.layer3.0.bn3.weight", "loss_segm_pl.impl.layer3.0.bn3.bias", "loss_segm_pl.impl.layer3.0.bn3.running_mean", "loss_segm_pl.impl.layer3.0.bn3.running_var", "loss_segm_pl.impl.layer3.0.bn3.num_batches_tracked", "loss_segm_pl.impl.layer3.0.downsample.0.weight", "loss_segm_pl.impl.layer3.0.downsample.1.weight", "loss_segm_pl.impl.layer3.0.downsample.1.bias", "loss_segm_pl.impl.layer3.0.downsample.1.running_mean", "loss_segm_pl.impl.layer3.0.downsample.1.running_var", "loss_segm_pl.impl.layer3.0.downsample.1.num_batches_tracked", "loss_segm_pl.impl.layer3.1.conv1.weight", "loss_segm_pl.impl.layer3.1.bn1.weight", "loss_segm_pl.impl.layer3.1.bn1.bias", "loss_segm_pl.impl.layer3.1.bn1.running_mean", "loss_segm_pl.impl.layer3.1.bn1.running_var", "loss_segm_pl.impl.layer3.1.bn1.num_batches_tracked", "loss_segm_pl.impl.layer3.1.conv2.weight", "loss_segm_pl.impl.layer3.1.bn2.weight", "loss_segm_pl.impl.layer3.1.bn2.bias", "loss_segm_pl.impl.layer3.1.bn2.running_mean", "loss_segm_pl.impl.layer3.1.bn2.running_var", "loss_segm_pl.impl.layer3.1.bn2.num_batches_tracked", "loss_segm_pl.impl.layer3.1.conv3.weight", "loss_segm_pl.impl.layer3.1.bn3.weight", "loss_segm_pl.impl.layer3.1.bn3.bias", "loss_segm_pl.impl.layer3.1.bn3.running_mean", "loss_segm_pl.impl.layer3.1.bn3.running_var", "loss_segm_pl.impl.layer3.1.bn3.num_batches_tracked", "loss_segm_pl.impl.layer3.2.conv1.weight", "loss_segm_pl.impl.layer3.2.bn1.weight", "loss_segm_pl.impl.layer3.2.bn1.bias", "loss_segm_pl.impl.layer3.2.bn1.running_mean", "loss_segm_pl.impl.layer3.2.bn1.running_var", "loss_segm_pl.impl.layer3.2.bn1.num_batches_tracked", "loss_segm_pl.impl.layer3.2.conv2.weight", "loss_segm_pl.impl.layer3.2.bn2.weight", "loss_segm_pl.impl.layer3.2.bn2.bias", "loss_segm_pl.impl.layer3.2.bn2.running_mean", "loss_segm_pl.impl.layer3.2.bn2.running_var", "loss_segm_pl.impl.layer3.2.bn2.num_batches_tracked", "loss_segm_pl.impl.layer3.2.conv3.weight", "loss_segm_pl.impl.layer3.2.bn3.weight", "loss_segm_pl.impl.layer3.2.bn3.bias", "loss_segm_pl.impl.layer3.2.bn3.running_mean", "loss_segm_pl.impl.layer3.2.bn3.running_var", "loss_segm_pl.impl.layer3.2.bn3.num_batches_tracked", "loss_segm_pl.impl.layer3.3.conv1.weight", "loss_segm_pl.impl.layer3.3.bn1.weight", "loss_segm_pl.impl.layer3.3.bn1.bias", "loss_segm_pl.impl.layer3.3.bn1.running_mean", "loss_segm_pl.impl.layer3.3.bn1.running_var", "loss_segm_pl.impl.layer3.3.bn1.num_batches_tracked", "loss_segm_pl.impl.layer3.3.conv2.weight", "loss_segm_pl.impl.layer3.3.bn2.weight", "loss_segm_pl.impl.layer3.3.bn2.bias", "loss_segm_pl.impl.layer3.3.bn2.running_mean", "loss_segm_pl.impl.layer3.3.bn2.running_var", "loss_segm_pl.impl.layer3.3.bn2.num_batches_tracked", "loss_segm_pl.impl.layer3.3.conv3.weight", "loss_segm_pl.impl.layer3.3.bn3.weight", "loss_segm_pl.impl.layer3.3.bn3.bias", "loss_segm_pl.impl.layer3.3.bn3.running_mean", "loss_segm_pl.impl.layer3.3.bn3.running_var", "loss_segm_pl.impl.layer3.3.bn3.num_batches_tracked", "loss_segm_pl.impl.layer3.4.conv1.weight", "loss_segm_pl.impl.layer3.4.bn1.weight", "loss_segm_pl.impl.layer3.4.bn1.bias", "loss_segm_pl.impl.layer3.4.bn1.running_mean", "loss_segm_pl.impl.layer3.4.bn1.running_var", "loss_segm_pl.impl.layer3.4.bn1.num_batches_tracked", "loss_segm_pl.impl.layer3.4.conv2.weight", "loss_segm_pl.impl.layer3.4.bn2.weight", "loss_segm_pl.impl.layer3.4.bn2.bias", "loss_segm_pl.impl.layer3.4.bn2.running_mean", "loss_segm_pl.impl.layer3.4.bn2.running_var", "loss_segm_pl.impl.layer3.4.bn2.num_batches_tracked", "loss_segm_pl.impl.layer3.4.conv3.weight", "loss_segm_pl.impl.layer3.4.bn3.weight", "loss_segm_pl.impl.layer3.4.bn3.bias", "loss_segm_pl.impl.layer3.4.bn3.running_mean", "loss_segm_pl.impl.layer3.4.bn3.running_var", "loss_segm_pl.impl.layer3.4.bn3.num_batches_tracked", "loss_segm_pl.impl.layer3.5.conv1.weight", "loss_segm_pl.impl.layer3.5.bn1.weight", "loss_segm_pl.impl.layer3.5.bn1.bias", "loss_segm_pl.impl.layer3.5.bn1.running_mean", "loss_segm_pl.impl.layer3.5.bn1.running_var", "loss_segm_pl.impl.layer3.5.bn1.num_batches_tracked", "loss_segm_pl.impl.layer3.5.conv2.weight", "loss_segm_pl.impl.layer3.5.bn2.weight", "loss_segm_pl.impl.layer3.5.bn2.bias", "loss_segm_pl.impl.layer3.5.bn2.running_mean", "loss_segm_pl.impl.layer3.5.bn2.running_var", "loss_segm_pl.impl.layer3.5.bn2.num_batches_tracked", "loss_segm_pl.impl.layer3.5.conv3.weight", "loss_segm_pl.impl.layer3.5.bn3.weight", "loss_segm_pl.impl.layer3.5.bn3.bias", "loss_segm_pl.impl.layer3.5.bn3.running_mean", "loss_segm_pl.impl.layer3.5.bn3.running_var", "loss_segm_pl.impl.layer3.5.bn3.num_batches_tracked", "loss_segm_pl.impl.layer4.0.conv1.weight", "loss_segm_pl.impl.layer4.0.bn1.weight", "loss_segm_pl.impl.layer4.0.bn1.bias", "loss_segm_pl.impl.layer4.0.bn1.running_mean", "loss_segm_pl.impl.layer4.0.bn1.running_var", "loss_segm_pl.impl.layer4.0.bn1.num_batches_tracked", "loss_segm_pl.impl.layer4.0.conv2.weight", "loss_segm_pl.impl.layer4.0.bn2.weight", "loss_segm_pl.impl.layer4.0.bn2.bias", "loss_segm_pl.impl.layer4.0.bn2.running_mean", "loss_segm_pl.impl.layer4.0.bn2.running_var", "loss_segm_pl.impl.layer4.0.bn2.num_batches_tracked", "loss_segm_pl.impl.layer4.0.conv3.weight", "loss_segm_pl.impl.layer4.0.bn3.weight", "loss_segm_pl.impl.layer4.0.bn3.bias", "loss_segm_pl.impl.layer4.0.bn3.running_mean", "loss_segm_pl.impl.layer4.0.bn3.running_var", "loss_segm_pl.impl.layer4.0.bn3.num_batches_tracked", "loss_segm_pl.impl.layer4.0.downsample.0.weight", "loss_segm_pl.impl.layer4.0.downsample.1.weight", "loss_segm_pl.impl.layer4.0.downsample.1.bias", "loss_segm_pl.impl.layer4.0.downsample.1.running_mean", "loss_segm_pl.impl.layer4.0.downsample.1.running_var", "loss_segm_pl.impl.layer4.0.downsample.1.num_batches_tracked", "loss_segm_pl.impl.layer4.1.conv1.weight", "loss_segm_pl.impl.layer4.1.bn1.weight", "loss_segm_pl.impl.layer4.1.bn1.bias", "loss_segm_pl.impl.layer4.1.bn1.running_mean", "loss_segm_pl.impl.layer4.1.bn1.running_var", "loss_segm_pl.impl.layer4.1.bn1.num_batches_tracked", "loss_segm_pl.impl.layer4.1.conv2.weight", "loss_segm_pl.impl.layer4.1.bn2.weight", "loss_segm_pl.impl.layer4.1.bn2.bias", "loss_segm_pl.impl.layer4.1.bn2.running_mean", "loss_segm_pl.impl.layer4.1.bn2.running_var", "loss_segm_pl.impl.layer4.1.bn2.num_batches_tracked", "loss_segm_pl.impl.layer4.1.conv3.weight", "loss_segm_pl.impl.layer4.1.bn3.weight", "loss_segm_pl.impl.layer4.1.bn3.bias", "loss_segm_pl.impl.layer4.1.bn3.running_mean", "loss_segm_pl.impl.layer4.1.bn3.running_var", "loss_segm_pl.impl.layer4.1.bn3.num_batches_tracked", "loss_segm_pl.impl.layer4.2.conv1.weight", "loss_segm_pl.impl.layer4.2.bn1.weight", "loss_segm_pl.impl.layer4.2.bn1.bias", "loss_segm_pl.impl.layer4.2.bn1.running_mean", "loss_segm_pl.impl.layer4.2.bn1.running_var", "loss_segm_pl.impl.layer4.2.bn1.num_batches_tracked", "loss_segm_pl.impl.layer4.2.conv2.weight", "loss_segm_pl.impl.layer4.2.bn2.weight", "loss_segm_pl.impl.layer4.2.bn2.bias", "loss_segm_pl.impl.layer4.2.bn2.running_mean", "loss_segm_pl.impl.layer4.2.bn2.running_var", "loss_segm_pl.impl.layer4.2.bn2.num_batches_tracked", "loss_segm_pl.impl.layer4.2.conv3.weight", "loss_segm_pl.impl.layer4.2.bn3.weight", "loss_segm_pl.impl.layer4.2.bn3.bias", "loss_segm_pl.impl.layer4.2.bn3.running_mean", "loss_segm_pl.impl.layer4.2.bn3.running_var", "loss_segm_pl.impl.layer4.2.bn3.num_batches_tracked".
```

**Comment by xv5kVu4FN** [comment]
@SofyanaB yes, that did it! I completely missed that discussion.

You're a lifesaver.

**Comment by qwexacc** [comment]
> @xv5kVu4FN I managed to solve the problem. Make sure that in the config file that is used for training: generator: ffc_resnet_075 And in lama/configs/training/generator/ffc_resnet_075.yaml n_blocks: 18
您好，我在训练的时候遇到了一个问题，可能是数据集路径的问题，可以向您请教一下嘛？

**Comment by qwexacc** [comment]
> 是的，做到了！我完全错过了那次讨论。
> 
> 你是救命稻草。

您好，我在训练的时候遇到了一个问题，可能是数据集路径的问题，可以向您请教一下嘛？
